### PR TITLE
Draft Reading List for Socratic 33

### PR DESCRIPTION
**Pull request by EvanWinget**
@casey had a bit of time free after work today so I started putting together a few links from Dec/Jan. Will try to add more later this week if I can. As always, please add/edit/delete whatever you want!

### CODE REVIEW

**Comment by casey** [comment]
(I haven't been consistent in the past, but I try to use single blank lines instead of trying to figure out when I should put double blank lines, e.g. between sections.)

**Comment by EvanWinget** [comment]
Ahh good call - thanks! 

I just made these changes. I have "allow edits by maintainers" on so users with write access to sfbitcoindevs/sfbitcoindevs can commit to this branch, but I don't see an option to allow edits by contributors.

**Comment by casey** [comment]
It might be because it's the master branch, which sometimes has rules to prevent pushes.

**Comment by casey** [comment]
LGTM, merged!

**Pull request merged**
